// Generated by scripts/build-icons.ts from icons/svg/dot.svg (Figma). Edit the icon in Figma and re-pull.
import type { SVGProps } from "react";

export function DotIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true" data-slot="icon" {...props}>
      <path d="M8 11C9.65685 11 11 9.65685 11 8C11 6.34315 9.65685 5 8 5C6.34315 5 5 6.34315 5 8C5 9.65685 6.34315 11 8 11Z" fill="currentColor" />
    </svg>
  );
}
