// Generated by scripts/build-icons.ts from icons/svg/info.svg (Figma). Edit the icon in Figma and re-pull.
import type { SVGProps } from "react";

export function InfoIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true" data-slot="icon" {...props}>
      <path d="M8 14.25C11.4518 14.25 14.25 11.4518 14.25 8C14.25 4.54822 11.4518 1.75 8 1.75C4.54822 1.75 1.75 4.54822 1.75 8C1.75 11.4518 4.54822 14.25 8 14.25Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M8 7.25V10.75" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M8.00001 5.9C8.49706 5.9 8.90001 5.49705 8.90001 5C8.90001 4.50294 8.49706 4.1 8.00001 4.1C7.50295 4.1 7.10001 4.50294 7.10001 5C7.10001 5.49705 7.50295 5.9 8.00001 5.9Z" fill="currentColor" />
    </svg>
  );
}
