// Generated by scripts/build-icons.ts from icons/svg/warning.svg (Figma). Edit the icon in Figma and re-pull.
import type { SVGProps } from "react";

export function WarningIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true" data-slot="icon" {...props}>
      <path d="M8 2.5L14 13H2L8 2.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M8 6.5V9.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M8.00001 12.15C8.49706 12.15 8.90001 11.7471 8.90001 11.25C8.90001 10.7529 8.49706 10.35 8.00001 10.35C7.50295 10.35 7.10001 10.7529 7.10001 11.25C7.10001 11.7471 7.50295 12.15 8.00001 12.15Z" fill="currentColor" />
    </svg>
  );
}
