// Turns icons/svg/*.svg (exported from Figma) into registry/icons/<name>.tsx React components.
// Usage: node scripts/build-icons.ts
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export function componentName(file: string): string {
  const base = file.replace(/\.svg$/, "");
  return base.replace(/(^|-)(\w)/g, (_, __, c: string) => c.toUpperCase()) + "Icon";
}

export function svgToTsx(name: string, svg: string): string {
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .trim()
    .replace(/"(black|#000|#000000)"/g, '"currentColor"')
    .replace(/\s([a-z]+(?:-[a-z]+)+)=/g, (_, attr: string) => " " + attr.replace(/-(\w)/g, (__, c: string) => c.toUpperCase()) + "=")
    .replace(/"\/>/g, '" />')
    .split("\n")
    .map((l) => `      ${l.trim()}`)
    .join("\n");
  return `// Generated by scripts/build-icons.ts from icons/svg/${name}.svg (Figma). Edit the icon in Figma and re-pull.
import type { SVGProps } from "react";

export function ${componentName(name)}(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true" data-slot="icon" {...props}>
${inner}
    </svg>
  );
}
`;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const src = join(root, "icons/svg");
  for (const file of readdirSync(src).filter((f) => f.endsWith(".svg"))) {
    const name = file.replace(/\.svg$/, "");
    writeFileSync(join(root, "registry/icons", `${name}.tsx`), svgToTsx(name, readFileSync(join(src, file), "utf8")));
  }
  console.log("icons generated");
}
